Remove orphaned Ixed instances for HashMap and Vector
fosskers/microlens-aeson pull request #27
Opened 2022-03-05 15:19 UTC by sjshuck

Fixes #4.

Also simplify Ixed instance for KeyMap, matching lens-aeson's impl.

2022-03-07 16:33 UTC, sjshuck commented
Can we hold off on releasing this until the scope of https://github.com/lens/lens-aeson/pull/42 stabilizes?  That PR appeared literally overnight and suggests possible other breaking changes upstream very soon.

2022-03-10 16:40 UTC, sjshuck commented
Okay, upstream has merged lens/lens-aeson#42, lens/lens-aeson#46, and lens/lens-aeson#47.  I think this PR can be merged, and then I'd be happy to work on porting other changes (such as `Index Value` changing from `Text` to `Key`).

2022-03-10 16:41 UTC, sjshuck commented
That is, porting other changes that would go into the next compatibility-breaking release of `microlens-aeson`.

2022-03-11 18:37 UTC, fosskers commented
So when I merge this, you're suggesting I shouldn't make a release right away?

2022-03-11 18:45 UTC, fosskers requested changes

2022-03-11 18:45 UTC, fosskers commented on src/Lens/Micro/Aeson.hs
> +  else pure a
Please turn the lambda into a named function within `where` clause and use guards instead of if-then-else.

2022-03-11 18:45 UTC, fosskers commented on src/Lens/Micro/Aeson/Internal.hs
>    {-# INLINE ix #-}
It this instance still necessary?

2022-03-11 18:48 UTC, fosskers commented
I've tested this PR and it works. If you make the small correction I suggested, I can merge this.

2022-03-11 18:51 UTC, fosskers commented on src/Lens/Micro/Aeson/Internal.hs
>    {-# INLINE ix #-}
Yes I suppose the remaining instances are necessary, since bridging the gap between `aeson` and `microlens` is precisely the purpose of this library.

2022-03-11 21:40 UTC, merged

2022-03-11 21:40 UTC, fosskers commented
Thanks!